apiVersion: v1
kind: Service
metadata:
  name: honeypot
  namespace: honeynet
  labels:
    app: honeypot
    component: deception
spec:
  selector:
    app: honeypot
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ftp
    port: 21
    targetPort: 21
  - name: ftps
    port: 990
    targetPort: 990
  type: ClusterIP
