apiVersion: v1
kind: Pod
metadata:
  name: honeypot-test
  namespace: honeynet
spec:
  nodeSelector:
    role: honeypot
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "sleep 3600"]