apiVersion: v1
kind: Pod
metadata:
  name: proxy-test
  namespace: honeynet
spec:
  nodeSelector:
    role: proxy
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "sleep 3600"]