apiVersion: v1
kind: Pod
metadata:
  name: siem-test
  namespace: siem
spec:
  nodeSelector:
    role: siem
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "sleep 3600"]