apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-to-honeypots
  namespace: honeynet
spec:
  podSelector:
    matchLabels:
      app: honeypot
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: proxy
